from __future__ import annotations

from typing import Protocol


class ComplaintSource(Protocol):
    def health(self) -> dict: ...

    def fetch(self, ack_no: str) -> dict | None: ...

    def referrals_today(self) -> list[dict]: ...

    def fetch_document(self, ack_no: str, document_type: str) -> dict | None: ...

    def fetch_narrative(self, ack_no: str) -> dict | None: ...
